name: notified_preferences_riverpod
description: A simple package providing glue methods between notified_preferences and flutter_riverpod.
version: 1.0.0
homepage: https://github.com/Kaiteki-Fedi/notified_preferences_riverpod
issue_tracker: https://github.com/Kaiteki-Fedi/notified_preferences_riverpod/issues

environment:
  sdk: '>=2.17.0 <3.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.0.0
  notified_preferences: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0